version: '3.8'
services:
  map-screenshot-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3119:3119"
    environment:
      - PORT=3119
    restart: unless-stopped
    volumes:
      - ./public:/app/public

  leaflet-map-viewer:
    build:
      context: ./leaflet-map-viewer
      dockerfile: Dockerfile
    ports:
      - "3118:3118"
    restart: unless-stopped
