version: '3.8'
services:
  map-screenshot-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./public:/app/public

  leaflet-map-viewer:
    build:
      context: ./leaflet-map-viewer
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
